require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'ReproSSLPinning' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])


  pod 'RNSslPinning', :path => '../node_modules/react-native-ssl-pinning'

  target 'ReproSSLPinningTests' do
    inherit! :complete
    # Pods for testing
  end

end

target 'ReproSSLPinning-tvOS' do
  # Pods for ReproSSLPinning-tvOS

  target 'ReproSSLPinning-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
